<a href="https://colab.research.google.com/github/cristiansaso23/Display-OLED/blob/main/Numpy_practica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# invocamos la libreria numpy
import numpy as np

Invocacion de una lista y un array

In [2]:
lista = [1,2,3]
print(lista)
print(type(lista))

[1, 2, 3]
<class 'list'>


In [3]:
vector = np.array([1,2,3])
print(vector)
print(type(vector))

[1 2 3]
<class 'numpy.ndarray'>


Indexación sobre una lista y un array (numpy)

![Ejercicio NumPy](https://www.programiz.com/sites/tutorial2program/files/numpy-array-negative-index.png)

In [4]:
lista[0]

1

In [5]:
vector[0]

np.int64(1)

In [6]:
lista[-1]

3

In [7]:
vector[-1]

np.int64(3)

In [8]:
vector[1:3:1]

array([2, 3])

In [9]:
vector[::-1]

array([3, 2, 1])

Condicionales

In [10]:
vector[vector > 1]

array([2, 3])

In [11]:
vector[vector < 1]

array([], dtype=int64)

In [12]:
vector[vector == 2]

array([2])

Creacion de vectores

In [13]:
vector_a = np.arange(10)
print(vector_a)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
vector_b = np.linspace(0,10,10)
print(vector_b)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [15]:
vector_c = np.zeros(10)
print(vector_c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
vector_d = np.ones(10)
print(vector_d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [17]:
vector_e = np.array([1,2,3,5,6,7,8])
print(vector_e)

[1 2 3 5 6 7 8]


Verificar dimensiones

In [18]:
vector_a.shape

(10,)

Calculos con vectores

In [19]:
# a + d
resultado1 =  vector_a + vector_d
resultado1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
# a - d
resultado2 = vector_a - vector_d
resultado2

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [21]:
# a^2
resultado3 = vector_a ** 2
resultado3

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
# a*2
resultado4 = vector_a * 2
resultado4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
# a + vector que tenga todos sus componentes igual 255
aux = vector_d * 255
resultado5 = vector_a + aux
print('Vector D ',vector_d)
print('Multiplicamos por 255 al Vector D ',aux)
print('Vector A ',vector_a)
print('Suma entre el vector A y el vector D multiplicado por 255 ',resultado5)

Vector D  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Multiplicamos por 255 al Vector D  [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
Vector A  [0 1 2 3 4 5 6 7 8 9]
Suma entre el vector A y el vector D multiplicado por 255  [255. 256. 257. 258. 259. 260. 261. 262. 263. 264.]


In [24]:
# raiz(a)
resultado =  np.sqrt(vector_a)
resultado

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

Funciones de agregacion


![Ejercicio NumPy](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhXjuo6_gVu1IYhnb8OroS5BvhaFNIiTY5NzwGRoYF23apFLjJzM3er8OFSFMAqcphKBtruQ8KOoAiqDU98usUU6rQvawaZJNXGJ3S2aSmuZg920RUf9LtTFiyBTY-e_4nFgHwNmleqvIA/s1600/4214_t2-3.PNG)


In [25]:
vector_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.sum(vector_a)

np.int64(45)

In [27]:
np.mean(vector_a)

np.float64(4.5)

In [28]:
np.min(vector_a)

np.int64(0)

In [29]:
np.max(vector_a)

np.int64(9)

Ejercicios

In [40]:
#Crear un array del 0 al 9
vector_b= np.linspace(0,9,10)
print(vector_b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#Crear un array de 10 ceros
b =

In [ ]:
#Crear un array de 10 unos
c =

In [ ]:
#Acceder al primer, último y penúltimo elemento del vector a


In [ ]:
#Extraer los elementos pares de un array del vector a


In [ ]:
#Multiplicar todos los elementos por 2 del vector a

In [ ]:
#Invertir un array

In [ ]:
#Calcular la suma de todos los elementos


In [ ]:
#Crear un array llamado d con 20 valores espaciados linealmente entre 0 y 1